import Head from 'next/head'
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import Grid from '@mui/material/Grid';
import styles from '@/styles/Home.module.css';
import Link from '@mui/material/Link';
import Button from '@mui/material/Button';
import React from 'react';
import { useRouter } from 'next/router';
import CardMedia from '@mui/material/CardMedia';
import { CardActionArea } from '@mui/material';


export default function Home() {

  const createTweet = async (payload: any) => {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_ENDPOINT}/tweet/tweets/`, {
        method: "POST",
        headers: { 
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            //'Authorization': `Token ${localStorage.getItem('token')}` 
        },
        body: JSON.stringify(payload),
    });
    const data = await res.json();
    console.log(data);
    if (res.ok) {
      console.log(res);
      return data;
    } else {
        throw new Error(`Error fetching data from API: ${data}`);
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box sx={{ width: '100%' }}>
          <Button variant="contained" onClick={() => createTweet({'content': 'test', 'label': '1'})}>Send Tweet</Button>
        </Box>
      </main>
    </>
  )
}
